version: '3'
services:
  gstant:
    image: gstant/general-server-assistant:latest
    container_name: general-server-assistant
    restart: always
    ports:
      - 9999:9999
    volumes:
      - /volume5/docker/guaxiaoqi/config:/home/gstant/general-server-assistant/config/
      - /volume5/docker/guaxiaoqi/plugins:/home/gstant/general-server-assistant/app/plugins
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: gstant
    volumes:
      - /volume5/docker/mongo/data/db:/data/db
      - /volume5/docker/mongo/etc/localtime:/etc/localtime
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
